import Navbar from '@/components/Navbar'
import createClient from "@/lib/supabase-server"
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar user={user} />
        <main className="container mx-auto flex min-h-screen w-full flex-1">
          {children}
        </main>
      </body>
    </html>
  )
}
