import './globals.css'

import Navbar from '@/components/Navbar'
import SupabaseAuthProvider from '@/components/providers/supabase-auth-provider'
import SupabaseProvider from '@/components/providers/supabase-provider'
import { createClient } from "@/lib/supabase-server"
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase = createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider>
          <SupabaseAuthProvider serverSession={session}>
            <Navbar loggedInUser={user} />
            <main className="container mx-auto flex min-h-screen w-full flex-1">
              {children}
            </main>
          </SupabaseAuthProvider>
        </SupabaseProvider>
        <Toaster />

      </body>
    </html>
  )
}
